### ISSUE TITLE
Kein Input in Public Repositories

### ISSUE THREAD

**Issue by tintinmaster** [JanPfenning/aoc2024#1]
AoC erlaubt es nicht den Input der Puzzles zu teilen

> Can I copy/redistribute part of Advent of Code? Please don't. Advent of Code is free to use, not free to copy. If you're posting a code repository somewhere, please don't include parts of Advent of Code like the puzzle text or your inputs. If you're making a website, please don't make it look like Advent of Code or name it something similar. [Source](https://adventofcode.com/2024/about#:~:text=Can%20I%20copy,it%20something%20similar.)

**Comment by JanPfenning** [comment]
resolved by rewriting history

**Comment by JanPfenning** [comment]
@tintinmaster but actually it only says "If you're posting a code repository somewhere, please don't include parts of Advent of Code like the puzzle text or your inputs." not something like "if the repository is public"
